/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goyeti

import (
	"encoding/json"
	"fmt"
)

// checks if the TagSearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagSearchResponse{}

// TagSearchResponse struct for TagSearchResponse
type TagSearchResponse struct {
	Tags                 []Tag `json:"tags"`
	Total                int32 `json:"total"`
	AdditionalProperties map[string]interface{}
}

type _TagSearchResponse TagSearchResponse

// NewTagSearchResponse instantiates a new TagSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagSearchResponse(tags []Tag, total int32) *TagSearchResponse {
	this := TagSearchResponse{}
	this.Tags = tags
	this.Total = total
	return &this
}

// NewTagSearchResponseWithDefaults instantiates a new TagSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagSearchResponseWithDefaults() *TagSearchResponse {
	this := TagSearchResponse{}
	return &this
}

// GetTags returns the Tags field value
func (o *TagSearchResponse) GetTags() []Tag {
	if o == nil {
		var ret []Tag
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *TagSearchResponse) GetTagsOk() ([]Tag, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *TagSearchResponse) SetTags(v []Tag) {
	o.Tags = v
}

// GetTotal returns the Total field value
func (o *TagSearchResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *TagSearchResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *TagSearchResponse) SetTotal(v int32) {
	o.Total = v
}

func (o TagSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagSearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tags"] = o.Tags
	toSerialize["total"] = o.Total

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TagSearchResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tags",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTagSearchResponse := _TagSearchResponse{}

	err = json.Unmarshal(data, &varTagSearchResponse)

	if err != nil {
		return err
	}

	*o = TagSearchResponse(varTagSearchResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tags")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTagSearchResponse struct {
	value *TagSearchResponse
	isSet bool
}

func (v NullableTagSearchResponse) Get() *TagSearchResponse {
	return v.value
}

func (v *NullableTagSearchResponse) Set(val *TagSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTagSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTagSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagSearchResponse(val *TagSearchResponse) *NullableTagSearchResponse {
	return &NullableTagSearchResponse{value: val, isSet: true}
}

func (v NullableTagSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
