/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goyeti

import (
	"encoding/json"
	"fmt"
)

// checks if the NewDFIQRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewDFIQRequest{}

// NewDFIQRequest struct for NewDFIQRequest
type NewDFIQRequest struct {
	DfiqYaml             string   `json:"dfiq_yaml"`
	DfiqType             DFIQType `json:"dfiq_type"`
	UpdateIndicators     *bool    `json:"update_indicators,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NewDFIQRequest NewDFIQRequest

// NewNewDFIQRequest instantiates a new NewDFIQRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewDFIQRequest(dfiqYaml string, dfiqType DFIQType) *NewDFIQRequest {
	this := NewDFIQRequest{}
	this.DfiqYaml = dfiqYaml
	this.DfiqType = dfiqType
	var updateIndicators bool = false
	this.UpdateIndicators = &updateIndicators
	return &this
}

// NewNewDFIQRequestWithDefaults instantiates a new NewDFIQRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewDFIQRequestWithDefaults() *NewDFIQRequest {
	this := NewDFIQRequest{}
	var updateIndicators bool = false
	this.UpdateIndicators = &updateIndicators
	return &this
}

// GetDfiqYaml returns the DfiqYaml field value
func (o *NewDFIQRequest) GetDfiqYaml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DfiqYaml
}

// GetDfiqYamlOk returns a tuple with the DfiqYaml field value
// and a boolean to check if the value has been set.
func (o *NewDFIQRequest) GetDfiqYamlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DfiqYaml, true
}

// SetDfiqYaml sets field value
func (o *NewDFIQRequest) SetDfiqYaml(v string) {
	o.DfiqYaml = v
}

// GetDfiqType returns the DfiqType field value
func (o *NewDFIQRequest) GetDfiqType() DFIQType {
	if o == nil {
		var ret DFIQType
		return ret
	}

	return o.DfiqType
}

// GetDfiqTypeOk returns a tuple with the DfiqType field value
// and a boolean to check if the value has been set.
func (o *NewDFIQRequest) GetDfiqTypeOk() (*DFIQType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DfiqType, true
}

// SetDfiqType sets field value
func (o *NewDFIQRequest) SetDfiqType(v DFIQType) {
	o.DfiqType = v
}

// GetUpdateIndicators returns the UpdateIndicators field value if set, zero value otherwise.
func (o *NewDFIQRequest) GetUpdateIndicators() bool {
	if o == nil || IsNil(o.UpdateIndicators) {
		var ret bool
		return ret
	}
	return *o.UpdateIndicators
}

// GetUpdateIndicatorsOk returns a tuple with the UpdateIndicators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewDFIQRequest) GetUpdateIndicatorsOk() (*bool, bool) {
	if o == nil || IsNil(o.UpdateIndicators) {
		return nil, false
	}
	return o.UpdateIndicators, true
}

// HasUpdateIndicators returns a boolean if a field has been set.
func (o *NewDFIQRequest) HasUpdateIndicators() bool {
	if o != nil && !IsNil(o.UpdateIndicators) {
		return true
	}

	return false
}

// SetUpdateIndicators gets a reference to the given bool and assigns it to the UpdateIndicators field.
func (o *NewDFIQRequest) SetUpdateIndicators(v bool) {
	o.UpdateIndicators = &v
}

func (o NewDFIQRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewDFIQRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dfiq_yaml"] = o.DfiqYaml
	toSerialize["dfiq_type"] = o.DfiqType
	if !IsNil(o.UpdateIndicators) {
		toSerialize["update_indicators"] = o.UpdateIndicators
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NewDFIQRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dfiq_yaml",
		"dfiq_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewDFIQRequest := _NewDFIQRequest{}

	err = json.Unmarshal(data, &varNewDFIQRequest)

	if err != nil {
		return err
	}

	*o = NewDFIQRequest(varNewDFIQRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "dfiq_yaml")
		delete(additionalProperties, "dfiq_type")
		delete(additionalProperties, "update_indicators")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNewDFIQRequest struct {
	value *NewDFIQRequest
	isSet bool
}

func (v NullableNewDFIQRequest) Get() *NewDFIQRequest {
	return v.value
}

func (v *NullableNewDFIQRequest) Set(val *NewDFIQRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNewDFIQRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNewDFIQRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewDFIQRequest(val *NewDFIQRequest) *NullableNewDFIQRequest {
	return &NullableNewDFIQRequest{value: val, isSet: true}
}

func (v NullableNewDFIQRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewDFIQRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
