/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goyeti

import (
	"encoding/json"
	"fmt"
)

// checks if the SearchUserResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchUserResponse{}

// SearchUserResponse struct for SearchUserResponse
type SearchUserResponse struct {
	Users                []User `json:"users"`
	Total                int32  `json:"total"`
	AdditionalProperties map[string]interface{}
}

type _SearchUserResponse SearchUserResponse

// NewSearchUserResponse instantiates a new SearchUserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchUserResponse(users []User, total int32) *SearchUserResponse {
	this := SearchUserResponse{}
	this.Users = users
	this.Total = total
	return &this
}

// NewSearchUserResponseWithDefaults instantiates a new SearchUserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchUserResponseWithDefaults() *SearchUserResponse {
	this := SearchUserResponse{}
	return &this
}

// GetUsers returns the Users field value
func (o *SearchUserResponse) GetUsers() []User {
	if o == nil {
		var ret []User
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *SearchUserResponse) GetUsersOk() ([]User, bool) {
	if o == nil {
		return nil, false
	}
	return o.Users, true
}

// SetUsers sets field value
func (o *SearchUserResponse) SetUsers(v []User) {
	o.Users = v
}

// GetTotal returns the Total field value
func (o *SearchUserResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *SearchUserResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *SearchUserResponse) SetTotal(v int32) {
	o.Total = v
}

func (o SearchUserResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchUserResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["users"] = o.Users
	toSerialize["total"] = o.Total

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchUserResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"users",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchUserResponse := _SearchUserResponse{}

	err = json.Unmarshal(data, &varSearchUserResponse)

	if err != nil {
		return err
	}

	*o = SearchUserResponse(varSearchUserResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "users")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSearchUserResponse struct {
	value *SearchUserResponse
	isSet bool
}

func (v NullableSearchUserResponse) Get() *SearchUserResponse {
	return v.value
}

func (v *NullableSearchUserResponse) Set(val *SearchUserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchUserResponse(val *SearchUserResponse) *NullableSearchUserResponse {
	return &NullableSearchUserResponse{value: val, isSet: true}
}

func (v NullableSearchUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
