/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goyeti

import (
	"encoding/json"
	"fmt"
)

// Hops struct for Hops
type Hops struct {
	Int32 *int32
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Hops) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into Int32
	err = json.Unmarshal(data, &dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			return nil // data stored in dst.Int32, return on the first match
		}
	} else {
		dst.Int32 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Hops)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Hops) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableHops struct {
	value *Hops
	isSet bool
}

func (v NullableHops) Get() *Hops {
	return v.value
}

func (v *NullableHops) Set(val *Hops) {
	v.value = val
	v.isSet = true
}

func (v NullableHops) IsSet() bool {
	return v.isSet
}

func (v *NullableHops) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHops(val *Hops) *NullableHops {
	return &NullableHops{value: val, isSet: true}
}

func (v NullableHops) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHops) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
