/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goyeti

import (
	"encoding/json"
	"fmt"
)

// checks if the DFIQValidateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DFIQValidateRequest{}

// DFIQValidateRequest struct for DFIQValidateRequest
type DFIQValidateRequest struct {
	DfiqYaml             string   `json:"dfiq_yaml"`
	DfiqType             DFIQType `json:"dfiq_type"`
	UpdateIndicators     *bool    `json:"update_indicators,omitempty"`
	CheckId              *bool    `json:"check_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DFIQValidateRequest DFIQValidateRequest

// NewDFIQValidateRequest instantiates a new DFIQValidateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDFIQValidateRequest(dfiqYaml string, dfiqType DFIQType) *DFIQValidateRequest {
	this := DFIQValidateRequest{}
	this.DfiqYaml = dfiqYaml
	this.DfiqType = dfiqType
	var updateIndicators bool = false
	this.UpdateIndicators = &updateIndicators
	var checkId bool = false
	this.CheckId = &checkId
	return &this
}

// NewDFIQValidateRequestWithDefaults instantiates a new DFIQValidateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDFIQValidateRequestWithDefaults() *DFIQValidateRequest {
	this := DFIQValidateRequest{}
	var updateIndicators bool = false
	this.UpdateIndicators = &updateIndicators
	var checkId bool = false
	this.CheckId = &checkId
	return &this
}

// GetDfiqYaml returns the DfiqYaml field value
func (o *DFIQValidateRequest) GetDfiqYaml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DfiqYaml
}

// GetDfiqYamlOk returns a tuple with the DfiqYaml field value
// and a boolean to check if the value has been set.
func (o *DFIQValidateRequest) GetDfiqYamlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DfiqYaml, true
}

// SetDfiqYaml sets field value
func (o *DFIQValidateRequest) SetDfiqYaml(v string) {
	o.DfiqYaml = v
}

// GetDfiqType returns the DfiqType field value
func (o *DFIQValidateRequest) GetDfiqType() DFIQType {
	if o == nil {
		var ret DFIQType
		return ret
	}

	return o.DfiqType
}

// GetDfiqTypeOk returns a tuple with the DfiqType field value
// and a boolean to check if the value has been set.
func (o *DFIQValidateRequest) GetDfiqTypeOk() (*DFIQType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DfiqType, true
}

// SetDfiqType sets field value
func (o *DFIQValidateRequest) SetDfiqType(v DFIQType) {
	o.DfiqType = v
}

// GetUpdateIndicators returns the UpdateIndicators field value if set, zero value otherwise.
func (o *DFIQValidateRequest) GetUpdateIndicators() bool {
	if o == nil || IsNil(o.UpdateIndicators) {
		var ret bool
		return ret
	}
	return *o.UpdateIndicators
}

// GetUpdateIndicatorsOk returns a tuple with the UpdateIndicators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DFIQValidateRequest) GetUpdateIndicatorsOk() (*bool, bool) {
	if o == nil || IsNil(o.UpdateIndicators) {
		return nil, false
	}
	return o.UpdateIndicators, true
}

// HasUpdateIndicators returns a boolean if a field has been set.
func (o *DFIQValidateRequest) HasUpdateIndicators() bool {
	if o != nil && !IsNil(o.UpdateIndicators) {
		return true
	}

	return false
}

// SetUpdateIndicators gets a reference to the given bool and assigns it to the UpdateIndicators field.
func (o *DFIQValidateRequest) SetUpdateIndicators(v bool) {
	o.UpdateIndicators = &v
}

// GetCheckId returns the CheckId field value if set, zero value otherwise.
func (o *DFIQValidateRequest) GetCheckId() bool {
	if o == nil || IsNil(o.CheckId) {
		var ret bool
		return ret
	}
	return *o.CheckId
}

// GetCheckIdOk returns a tuple with the CheckId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DFIQValidateRequest) GetCheckIdOk() (*bool, bool) {
	if o == nil || IsNil(o.CheckId) {
		return nil, false
	}
	return o.CheckId, true
}

// HasCheckId returns a boolean if a field has been set.
func (o *DFIQValidateRequest) HasCheckId() bool {
	if o != nil && !IsNil(o.CheckId) {
		return true
	}

	return false
}

// SetCheckId gets a reference to the given bool and assigns it to the CheckId field.
func (o *DFIQValidateRequest) SetCheckId(v bool) {
	o.CheckId = &v
}

func (o DFIQValidateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DFIQValidateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dfiq_yaml"] = o.DfiqYaml
	toSerialize["dfiq_type"] = o.DfiqType
	if !IsNil(o.UpdateIndicators) {
		toSerialize["update_indicators"] = o.UpdateIndicators
	}
	if !IsNil(o.CheckId) {
		toSerialize["check_id"] = o.CheckId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DFIQValidateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dfiq_yaml",
		"dfiq_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDFIQValidateRequest := _DFIQValidateRequest{}

	err = json.Unmarshal(data, &varDFIQValidateRequest)

	if err != nil {
		return err
	}

	*o = DFIQValidateRequest(varDFIQValidateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "dfiq_yaml")
		delete(additionalProperties, "dfiq_type")
		delete(additionalProperties, "update_indicators")
		delete(additionalProperties, "check_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDFIQValidateRequest struct {
	value *DFIQValidateRequest
	isSet bool
}

func (v NullableDFIQValidateRequest) Get() *DFIQValidateRequest {
	return v.value
}

func (v *NullableDFIQValidateRequest) Set(val *DFIQValidateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDFIQValidateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDFIQValidateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDFIQValidateRequest(val *DFIQValidateRequest) *NullableDFIQValidateRequest {
	return &NullableDFIQValidateRequest{value: val, isSet: true}
}

func (v NullableDFIQValidateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDFIQValidateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
