/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goyeti

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the IntrusionSetOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntrusionSetOutput{}

// IntrusionSetOutput struct for IntrusionSetOutput
type IntrusionSetOutput struct {
	Type                    *string                          `json:"type,omitempty"`
	Name                    string                           `json:"name"`
	Description             *string                          `json:"description,omitempty"`
	Context                 []map[string]interface{}         `json:"context,omitempty"`
	Created                 *time.Time                       `json:"created,omitempty"`
	Modified                *time.Time                       `json:"modified,omitempty"`
	Aliases                 []string                         `json:"aliases,omitempty"`
	FirstSeen               *time.Time                       `json:"first_seen,omitempty"`
	LastSeen                *time.Time                       `json:"last_seen,omitempty"`
	Id                      string                           `json:"id"`
	Tags                    map[string]TagRelationshipOutput `json:"tags"`
	RootType                string                           `json:"root_type"`
	RelatedObservablesCount int32                            `json:"related_observables_count"`
}

type _IntrusionSetOutput IntrusionSetOutput

// NewIntrusionSetOutput instantiates a new IntrusionSetOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntrusionSetOutput(name string, id string, tags map[string]TagRelationshipOutput, rootType string, relatedObservablesCount int32) *IntrusionSetOutput {
	this := IntrusionSetOutput{}
	var type_ string = "intrusion-set"
	this.Type = &type_
	this.Name = name
	var description string = ""
	this.Description = &description
	this.Id = id
	this.Tags = tags
	this.RootType = rootType
	this.RelatedObservablesCount = relatedObservablesCount
	return &this
}

// NewIntrusionSetOutputWithDefaults instantiates a new IntrusionSetOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntrusionSetOutputWithDefaults() *IntrusionSetOutput {
	this := IntrusionSetOutput{}
	var type_ string = "intrusion-set"
	this.Type = &type_
	var description string = ""
	this.Description = &description
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IntrusionSetOutput) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntrusionSetOutput) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IntrusionSetOutput) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *IntrusionSetOutput) SetType(v string) {
	o.Type = &v
}

// GetName returns the Name field value
func (o *IntrusionSetOutput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *IntrusionSetOutput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *IntrusionSetOutput) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *IntrusionSetOutput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntrusionSetOutput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *IntrusionSetOutput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *IntrusionSetOutput) SetDescription(v string) {
	o.Description = &v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *IntrusionSetOutput) GetContext() []map[string]interface{} {
	if o == nil || IsNil(o.Context) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntrusionSetOutput) GetContextOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *IntrusionSetOutput) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given []map[string]interface{} and assigns it to the Context field.
func (o *IntrusionSetOutput) SetContext(v []map[string]interface{}) {
	o.Context = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *IntrusionSetOutput) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntrusionSetOutput) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *IntrusionSetOutput) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *IntrusionSetOutput) SetCreated(v time.Time) {
	o.Created = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *IntrusionSetOutput) GetModified() time.Time {
	if o == nil || IsNil(o.Modified) {
		var ret time.Time
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntrusionSetOutput) GetModifiedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Modified) {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *IntrusionSetOutput) HasModified() bool {
	if o != nil && !IsNil(o.Modified) {
		return true
	}

	return false
}

// SetModified gets a reference to the given time.Time and assigns it to the Modified field.
func (o *IntrusionSetOutput) SetModified(v time.Time) {
	o.Modified = &v
}

// GetAliases returns the Aliases field value if set, zero value otherwise.
func (o *IntrusionSetOutput) GetAliases() []string {
	if o == nil || IsNil(o.Aliases) {
		var ret []string
		return ret
	}
	return o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntrusionSetOutput) GetAliasesOk() ([]string, bool) {
	if o == nil || IsNil(o.Aliases) {
		return nil, false
	}
	return o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *IntrusionSetOutput) HasAliases() bool {
	if o != nil && !IsNil(o.Aliases) {
		return true
	}

	return false
}

// SetAliases gets a reference to the given []string and assigns it to the Aliases field.
func (o *IntrusionSetOutput) SetAliases(v []string) {
	o.Aliases = v
}

// GetFirstSeen returns the FirstSeen field value if set, zero value otherwise.
func (o *IntrusionSetOutput) GetFirstSeen() time.Time {
	if o == nil || IsNil(o.FirstSeen) {
		var ret time.Time
		return ret
	}
	return *o.FirstSeen
}

// GetFirstSeenOk returns a tuple with the FirstSeen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntrusionSetOutput) GetFirstSeenOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FirstSeen) {
		return nil, false
	}
	return o.FirstSeen, true
}

// HasFirstSeen returns a boolean if a field has been set.
func (o *IntrusionSetOutput) HasFirstSeen() bool {
	if o != nil && !IsNil(o.FirstSeen) {
		return true
	}

	return false
}

// SetFirstSeen gets a reference to the given time.Time and assigns it to the FirstSeen field.
func (o *IntrusionSetOutput) SetFirstSeen(v time.Time) {
	o.FirstSeen = &v
}

// GetLastSeen returns the LastSeen field value if set, zero value otherwise.
func (o *IntrusionSetOutput) GetLastSeen() time.Time {
	if o == nil || IsNil(o.LastSeen) {
		var ret time.Time
		return ret
	}
	return *o.LastSeen
}

// GetLastSeenOk returns a tuple with the LastSeen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntrusionSetOutput) GetLastSeenOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastSeen) {
		return nil, false
	}
	return o.LastSeen, true
}

// HasLastSeen returns a boolean if a field has been set.
func (o *IntrusionSetOutput) HasLastSeen() bool {
	if o != nil && !IsNil(o.LastSeen) {
		return true
	}

	return false
}

// SetLastSeen gets a reference to the given time.Time and assigns it to the LastSeen field.
func (o *IntrusionSetOutput) SetLastSeen(v time.Time) {
	o.LastSeen = &v
}

// GetId returns the Id field value
func (o *IntrusionSetOutput) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IntrusionSetOutput) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IntrusionSetOutput) SetId(v string) {
	o.Id = v
}

// GetTags returns the Tags field value
func (o *IntrusionSetOutput) GetTags() map[string]TagRelationshipOutput {
	if o == nil {
		var ret map[string]TagRelationshipOutput
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *IntrusionSetOutput) GetTagsOk() (map[string]TagRelationshipOutput, bool) {
	if o == nil {
		return map[string]TagRelationshipOutput{}, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *IntrusionSetOutput) SetTags(v map[string]TagRelationshipOutput) {
	o.Tags = v
}

// GetRootType returns the RootType field value
func (o *IntrusionSetOutput) GetRootType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RootType
}

// GetRootTypeOk returns a tuple with the RootType field value
// and a boolean to check if the value has been set.
func (o *IntrusionSetOutput) GetRootTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RootType, true
}

// SetRootType sets field value
func (o *IntrusionSetOutput) SetRootType(v string) {
	o.RootType = v
}

// GetRelatedObservablesCount returns the RelatedObservablesCount field value
func (o *IntrusionSetOutput) GetRelatedObservablesCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RelatedObservablesCount
}

// GetRelatedObservablesCountOk returns a tuple with the RelatedObservablesCount field value
// and a boolean to check if the value has been set.
func (o *IntrusionSetOutput) GetRelatedObservablesCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RelatedObservablesCount, true
}

// SetRelatedObservablesCount sets field value
func (o *IntrusionSetOutput) SetRelatedObservablesCount(v int32) {
	o.RelatedObservablesCount = v
}

func (o IntrusionSetOutput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntrusionSetOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Modified) {
		toSerialize["modified"] = o.Modified
	}
	if !IsNil(o.Aliases) {
		toSerialize["aliases"] = o.Aliases
	}
	if !IsNil(o.FirstSeen) {
		toSerialize["first_seen"] = o.FirstSeen
	}
	if !IsNil(o.LastSeen) {
		toSerialize["last_seen"] = o.LastSeen
	}
	toSerialize["id"] = o.Id
	toSerialize["tags"] = o.Tags
	toSerialize["root_type"] = o.RootType
	toSerialize["related_observables_count"] = o.RelatedObservablesCount
	return toSerialize, nil
}

func (o *IntrusionSetOutput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"id",
		"tags",
		"root_type",
		"related_observables_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntrusionSetOutput := _IntrusionSetOutput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIntrusionSetOutput)

	if err != nil {
		return err
	}

	*o = IntrusionSetOutput(varIntrusionSetOutput)

	return err
}

type NullableIntrusionSetOutput struct {
	value *IntrusionSetOutput
	isSet bool
}

func (v NullableIntrusionSetOutput) Get() *IntrusionSetOutput {
	return v.value
}

func (v *NullableIntrusionSetOutput) Set(val *IntrusionSetOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableIntrusionSetOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableIntrusionSetOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntrusionSetOutput(val *IntrusionSetOutput) *NullableIntrusionSetOutput {
	return &NullableIntrusionSetOutput{value: val, isSet: true}
}

func (v NullableIntrusionSetOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntrusionSetOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
