/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goyeti

import (
	"encoding/json"
	"fmt"
)

// checks if the ObservableTagResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObservableTagResponse{}

// ObservableTagResponse struct for ObservableTagResponse
type ObservableTagResponse struct {
	Tagged               int32                                       `json:"tagged"`
	Tags                 map[string]map[string]TagRelationshipOutput `json:"tags"`
	AdditionalProperties map[string]interface{}
}

type _ObservableTagResponse ObservableTagResponse

// NewObservableTagResponse instantiates a new ObservableTagResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObservableTagResponse(tagged int32, tags map[string]map[string]TagRelationshipOutput) *ObservableTagResponse {
	this := ObservableTagResponse{}
	this.Tagged = tagged
	this.Tags = tags
	return &this
}

// NewObservableTagResponseWithDefaults instantiates a new ObservableTagResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObservableTagResponseWithDefaults() *ObservableTagResponse {
	this := ObservableTagResponse{}
	return &this
}

// GetTagged returns the Tagged field value
func (o *ObservableTagResponse) GetTagged() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Tagged
}

// GetTaggedOk returns a tuple with the Tagged field value
// and a boolean to check if the value has been set.
func (o *ObservableTagResponse) GetTaggedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tagged, true
}

// SetTagged sets field value
func (o *ObservableTagResponse) SetTagged(v int32) {
	o.Tagged = v
}

// GetTags returns the Tags field value
func (o *ObservableTagResponse) GetTags() map[string]map[string]TagRelationshipOutput {
	if o == nil {
		var ret map[string]map[string]TagRelationshipOutput
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *ObservableTagResponse) GetTagsOk() (map[string]map[string]TagRelationshipOutput, bool) {
	if o == nil {
		return map[string]map[string]TagRelationshipOutput{}, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *ObservableTagResponse) SetTags(v map[string]map[string]TagRelationshipOutput) {
	o.Tags = v
}

func (o ObservableTagResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObservableTagResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tagged"] = o.Tagged
	toSerialize["tags"] = o.Tags

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ObservableTagResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tagged",
		"tags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObservableTagResponse := _ObservableTagResponse{}

	err = json.Unmarshal(data, &varObservableTagResponse)

	if err != nil {
		return err
	}

	*o = ObservableTagResponse(varObservableTagResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tagged")
		delete(additionalProperties, "tags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableObservableTagResponse struct {
	value *ObservableTagResponse
	isSet bool
}

func (v NullableObservableTagResponse) Get() *ObservableTagResponse {
	return v.value
}

func (v *NullableObservableTagResponse) Set(val *ObservableTagResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableObservableTagResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableObservableTagResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObservableTagResponse(val *ObservableTagResponse) *NullableObservableTagResponse {
	return &NullableObservableTagResponse{value: val, isSet: true}
}

func (v NullableObservableTagResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObservableTagResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
