/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goyeti

import (
	"encoding/json"
	"fmt"
)

// ObservableTypeInput the model 'ObservableTypeInput'
type ObservableTypeInput string

// List of ObservableType-Input
const (
	IMPHASH      ObservableTypeInput = "imphash"
	PACKAGE      ObservableTypeInput = "package"
	GENERIC      ObservableTypeInput = "generic"
	JA3          ObservableTypeInput = "ja3"
	USER_ACCOUNT ObservableTypeInput = "user_account"
	HOSTNAME     ObservableTypeInput = "hostname"
	JARM         ObservableTypeInput = "jarm"
	IPV4         ObservableTypeInput = "ipv4"
	COMMAND_LINE ObservableTypeInput = "command_line"
	TLSH         ObservableTypeInput = "tlsh"
	MD5          ObservableTypeInput = "md5"
	SHA256       ObservableTypeInput = "sha256"
	IBAN         ObservableTypeInput = "iban"
	PATH         ObservableTypeInput = "path"
	EMAIL        ObservableTypeInput = "email"
	CIDR         ObservableTypeInput = "cidr"
	ASN          ObservableTypeInput = "asn"
	CERTIFICATE  ObservableTypeInput = "certificate"
	USER_AGENT   ObservableTypeInput = "user_agent"
	REGISTRY_KEY ObservableTypeInput = "registry_key"
	DOCKER_IMAGE ObservableTypeInput = "docker_image"
	URL          ObservableTypeInput = "url"
	FILE         ObservableTypeInput = "file"
	NAMED_PIPE   ObservableTypeInput = "named_pipe"
	BIC          ObservableTypeInput = "bic"
	SSDEEP       ObservableTypeInput = "ssdeep"
	MUTEX        ObservableTypeInput = "mutex"
	SHA1         ObservableTypeInput = "sha1"
	MAC_ADDRESS  ObservableTypeInput = "mac_address"
	WALLET       ObservableTypeInput = "wallet"
	IPV6         ObservableTypeInput = "ipv6"
	GUESS        ObservableTypeInput = "guess"
)

// All allowed values of ObservableTypeInput enum
var AllowedObservableTypeInputEnumValues = []ObservableTypeInput{
	"imphash",
	"package",
	"generic",
	"ja3",
	"user_account",
	"hostname",
	"jarm",
	"ipv4",
	"command_line",
	"tlsh",
	"md5",
	"sha256",
	"iban",
	"path",
	"email",
	"cidr",
	"asn",
	"certificate",
	"user_agent",
	"registry_key",
	"docker_image",
	"url",
	"file",
	"named_pipe",
	"bic",
	"ssdeep",
	"mutex",
	"sha1",
	"mac_address",
	"wallet",
	"ipv6",
	"guess",
}

func (v *ObservableTypeInput) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ObservableTypeInput(value)
	for _, existing := range AllowedObservableTypeInputEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ObservableTypeInput", value)
}

// NewObservableTypeInputFromValue returns a pointer to a valid ObservableTypeInput
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewObservableTypeInputFromValue(v string) (*ObservableTypeInput, error) {
	ev := ObservableTypeInput(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ObservableTypeInput: valid values are %v", v, AllowedObservableTypeInputEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ObservableTypeInput) IsValid() bool {
	for _, existing := range AllowedObservableTypeInputEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ObservableType-Input value
func (v ObservableTypeInput) Ptr() *ObservableTypeInput {
	return &v
}

type NullableObservableTypeInput struct {
	value *ObservableTypeInput
	isSet bool
}

func (v NullableObservableTypeInput) Get() *ObservableTypeInput {
	return v.value
}

func (v *NullableObservableTypeInput) Set(val *ObservableTypeInput) {
	v.value = val
	v.isSet = true
}

func (v NullableObservableTypeInput) IsSet() bool {
	return v.isSet
}

func (v *NullableObservableTypeInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObservableTypeInput(val *ObservableTypeInput) *NullableObservableTypeInput {
	return &NullableObservableTypeInput{value: val, isSet: true}
}

func (v NullableObservableTypeInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObservableTypeInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
