/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goyeti

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ThreatActorInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThreatActorInput{}

// ThreatActorInput struct for ThreatActorInput
type ThreatActorInput struct {
	Type             *string                  `json:"type,omitempty"`
	Name             string                   `json:"name"`
	Description      *string                  `json:"description,omitempty"`
	Context          []map[string]interface{} `json:"context,omitempty"`
	Created          *time.Time               `json:"created,omitempty"`
	Modified         *time.Time               `json:"modified,omitempty"`
	ThreatActorTypes []string                 `json:"threat_actor_types,omitempty"`
	Aliases          []string                 `json:"aliases,omitempty"`
	FirstSeen        *time.Time               `json:"first_seen,omitempty"`
	LastSeen         *time.Time               `json:"last_seen,omitempty"`
}

type _ThreatActorInput ThreatActorInput

// NewThreatActorInput instantiates a new ThreatActorInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThreatActorInput(name string) *ThreatActorInput {
	this := ThreatActorInput{}
	var type_ string = "threat-actor"
	this.Type = &type_
	this.Name = name
	var description string = ""
	this.Description = &description
	return &this
}

// NewThreatActorInputWithDefaults instantiates a new ThreatActorInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThreatActorInputWithDefaults() *ThreatActorInput {
	this := ThreatActorInput{}
	var type_ string = "threat-actor"
	this.Type = &type_
	var description string = ""
	this.Description = &description
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ThreatActorInput) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatActorInput) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ThreatActorInput) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ThreatActorInput) SetType(v string) {
	o.Type = &v
}

// GetName returns the Name field value
func (o *ThreatActorInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ThreatActorInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ThreatActorInput) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ThreatActorInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatActorInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ThreatActorInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ThreatActorInput) SetDescription(v string) {
	o.Description = &v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *ThreatActorInput) GetContext() []map[string]interface{} {
	if o == nil || IsNil(o.Context) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatActorInput) GetContextOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *ThreatActorInput) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given []map[string]interface{} and assigns it to the Context field.
func (o *ThreatActorInput) SetContext(v []map[string]interface{}) {
	o.Context = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ThreatActorInput) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatActorInput) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ThreatActorInput) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *ThreatActorInput) SetCreated(v time.Time) {
	o.Created = &v
}

// GetModified returns the Modified field value if set, zero value otherwise.
func (o *ThreatActorInput) GetModified() time.Time {
	if o == nil || IsNil(o.Modified) {
		var ret time.Time
		return ret
	}
	return *o.Modified
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatActorInput) GetModifiedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Modified) {
		return nil, false
	}
	return o.Modified, true
}

// HasModified returns a boolean if a field has been set.
func (o *ThreatActorInput) HasModified() bool {
	if o != nil && !IsNil(o.Modified) {
		return true
	}

	return false
}

// SetModified gets a reference to the given time.Time and assigns it to the Modified field.
func (o *ThreatActorInput) SetModified(v time.Time) {
	o.Modified = &v
}

// GetThreatActorTypes returns the ThreatActorTypes field value if set, zero value otherwise.
func (o *ThreatActorInput) GetThreatActorTypes() []string {
	if o == nil || IsNil(o.ThreatActorTypes) {
		var ret []string
		return ret
	}
	return o.ThreatActorTypes
}

// GetThreatActorTypesOk returns a tuple with the ThreatActorTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatActorInput) GetThreatActorTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.ThreatActorTypes) {
		return nil, false
	}
	return o.ThreatActorTypes, true
}

// HasThreatActorTypes returns a boolean if a field has been set.
func (o *ThreatActorInput) HasThreatActorTypes() bool {
	if o != nil && !IsNil(o.ThreatActorTypes) {
		return true
	}

	return false
}

// SetThreatActorTypes gets a reference to the given []string and assigns it to the ThreatActorTypes field.
func (o *ThreatActorInput) SetThreatActorTypes(v []string) {
	o.ThreatActorTypes = v
}

// GetAliases returns the Aliases field value if set, zero value otherwise.
func (o *ThreatActorInput) GetAliases() []string {
	if o == nil || IsNil(o.Aliases) {
		var ret []string
		return ret
	}
	return o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatActorInput) GetAliasesOk() ([]string, bool) {
	if o == nil || IsNil(o.Aliases) {
		return nil, false
	}
	return o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *ThreatActorInput) HasAliases() bool {
	if o != nil && !IsNil(o.Aliases) {
		return true
	}

	return false
}

// SetAliases gets a reference to the given []string and assigns it to the Aliases field.
func (o *ThreatActorInput) SetAliases(v []string) {
	o.Aliases = v
}

// GetFirstSeen returns the FirstSeen field value if set, zero value otherwise.
func (o *ThreatActorInput) GetFirstSeen() time.Time {
	if o == nil || IsNil(o.FirstSeen) {
		var ret time.Time
		return ret
	}
	return *o.FirstSeen
}

// GetFirstSeenOk returns a tuple with the FirstSeen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatActorInput) GetFirstSeenOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FirstSeen) {
		return nil, false
	}
	return o.FirstSeen, true
}

// HasFirstSeen returns a boolean if a field has been set.
func (o *ThreatActorInput) HasFirstSeen() bool {
	if o != nil && !IsNil(o.FirstSeen) {
		return true
	}

	return false
}

// SetFirstSeen gets a reference to the given time.Time and assigns it to the FirstSeen field.
func (o *ThreatActorInput) SetFirstSeen(v time.Time) {
	o.FirstSeen = &v
}

// GetLastSeen returns the LastSeen field value if set, zero value otherwise.
func (o *ThreatActorInput) GetLastSeen() time.Time {
	if o == nil || IsNil(o.LastSeen) {
		var ret time.Time
		return ret
	}
	return *o.LastSeen
}

// GetLastSeenOk returns a tuple with the LastSeen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThreatActorInput) GetLastSeenOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastSeen) {
		return nil, false
	}
	return o.LastSeen, true
}

// HasLastSeen returns a boolean if a field has been set.
func (o *ThreatActorInput) HasLastSeen() bool {
	if o != nil && !IsNil(o.LastSeen) {
		return true
	}

	return false
}

// SetLastSeen gets a reference to the given time.Time and assigns it to the LastSeen field.
func (o *ThreatActorInput) SetLastSeen(v time.Time) {
	o.LastSeen = &v
}

func (o ThreatActorInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThreatActorInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Modified) {
		toSerialize["modified"] = o.Modified
	}
	if !IsNil(o.ThreatActorTypes) {
		toSerialize["threat_actor_types"] = o.ThreatActorTypes
	}
	if !IsNil(o.Aliases) {
		toSerialize["aliases"] = o.Aliases
	}
	if !IsNil(o.FirstSeen) {
		toSerialize["first_seen"] = o.FirstSeen
	}
	if !IsNil(o.LastSeen) {
		toSerialize["last_seen"] = o.LastSeen
	}
	return toSerialize, nil
}

func (o *ThreatActorInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varThreatActorInput := _ThreatActorInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varThreatActorInput)

	if err != nil {
		return err
	}

	*o = ThreatActorInput(varThreatActorInput)

	return err
}

type NullableThreatActorInput struct {
	value *ThreatActorInput
	isSet bool
}

func (v NullableThreatActorInput) Get() *ThreatActorInput {
	return v.value
}

func (v *NullableThreatActorInput) Set(val *ThreatActorInput) {
	v.value = val
	v.isSet = true
}

func (v NullableThreatActorInput) IsSet() bool {
	return v.isSet
}

func (v *NullableThreatActorInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThreatActorInput(val *ThreatActorInput) *NullableThreatActorInput {
	return &NullableThreatActorInput{value: val, isSet: true}
}

func (v NullableThreatActorInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThreatActorInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
